### ISSUE TITLE
ngssc not working when pre gzip all files for text compresion on the nginx container

### ISSUE THREAD

**Issue by ursforrer** [kyubisation/angular-server-side-configuration#84]
If we want to use text compresion on the nginx container and precompress all files using gzip, the ngssc isn't working correcly anymore. If we remove the line with RUN gzip and dynamically compress the files, ngssc is working correctly. Is there any clue why this is?

Dockerfile
`FROM --platform=linux/amd64 nginx:1.24.0

ADD https://github.com/kyubisation/angular-server-side-configuration/releases/download/v15.1.0/ngssc_64bit /usr/sbin/ngssc
RUN chmod +x /usr/sbin/ngssc

# Add ngssc init script
COPY nginx/ngssc.sh /docker-entrypoint.d/ngssc.sh
RUN chmod +x /docker-entrypoint.d/ngssc.sh

COPY nginx/nginx.conf.template /etc/nginx/conf.d/default.conf.template

# Copy the build output to replace the default nginx contents.
COPY dist/ /usr/share/nginx/html

# Pre GZIP all files
RUN gzip --recursive --keep /usr/share/nginx/html/*

ENV API_SUBDOMAIN="api"
ENV EDITOR_SUBDOMAIN="editor"
ENV TRANSLATION_SUBDOMAIN="lang"
ENV IMG_SUBDOMAIN="img"
ENV MARKERMAPS_SUBDOMAIN="tiling"

# Expose port 80
EXPOSE 80`

**Comment by kyubisation** [comment]
Hello @ursforrer 
ngssc only looks for the uncompressed index.html (or other defined pattern) and ignores any gzipped or brotlified index.html files.
In your case I would assume it works, when you disable compression on your client, but does not work, when the consuming client supports compression options.

In order to fix this, you should exclude any "index.html" from your gzipping.
It is unforunately not easily possible to support pre-compressed index.html with ngssc, as this would require adding the brotli and gzip algorithm to the binary, which would bloat it unnecessarily.

**Comment by kyubisation** [comment]
Hello @ursforrer 
Is this issue still active?

**Comment by kyubisation** [comment]
Feel free to reopen this issue, if you still have questions about this.
